version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:953106843634:task-definition/aws-hello-world:2"
        LoadBalancerInfo:
          ContainerName: "aws-hello-world-container"
          ContainerPort: "80"
        PlatformVersion: "LATEST"